# Generated by Django 2.2.2 on 2019-08-27 00:06

import admin01.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_show', models.IntegerField(default=1)),
                ('sort', models.IntegerField(default=1)),
                ('type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'banner',
            },
            bases=(admin01.models.Base, models.Model),
        ),
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('pid', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=1)),
                ('top_id', models.IntegerField(default=0)),
                ('is_recommend', models.IntegerField(default=1)),
                ('pic', models.CharField(default=0, max_length=245)),
            ],
            options={
                'db_table': 'cate',
            },
            bases=(models.Model, admin01.models.Base),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('is_recommend', models.IntegerField(default=0)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'news',
            },
            bases=(admin01.models.Base, models.Model),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.CharField(default='', max_length=255)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'resource',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.IntegerField(default=0)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin01.Role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('is_recommend', models.IntegerField(default=1)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin01.Cate')),
            ],
            options={
                'db_table': 'tag',
            },
            bases=(models.Model, admin01.models.Base),
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=999999, max_digits=64)),
                ('pic', models.CharField(default='', max_length=250)),
                ('stock', models.IntegerField(default=0)),
                ('lock_stock', models.IntegerField(default=0)),
                ('is_recommend', models.IntegerField(default=1)),
                ('top_id', models.IntegerField(default=0)),
                ('comment_time', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('cid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin01.Cate')),
                ('tid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin01.Tags')),
            ],
            options={
                'db_table': 'goods',
            },
            bases=(admin01.models.Base, models.Model),
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin01.Resource')),
                ('role_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin01.Role')),
            ],
            options={
                'db_table': 'connect',
            },
        ),
    ]
