# Generated by Django 2.2.2 on 2019-08-27 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0003_goods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
