# Generated by Django 2.2.2 on 2019-08-27 00:11

import admin01.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0004_delete_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(default='', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=999999, max_digits=64)),
                ('pic', models.CharField(default='', max_length=250)),
                ('stock', models.IntegerField(default=0)),
                ('lock_stock', models.IntegerField(default=0)),
                ('is_recommend', models.IntegerField(default=1)),
                ('top_id', models.IntegerField(default=0)),
                ('comment_time', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('cid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin01.Cate')),
                ('tid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='admin01.Tags')),
            ],
            options={
                'db_table': 'goods',
            },
            bases=(admin01.models.Base, models.Model),
        ),
    ]
