# Generated by Django 2.2.2 on 2019-08-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin01', '0007_connect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
