# Generated by Django 2.2.2 on 2019-08-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('goods_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('goods_name', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
