# Generated by Django 2.2.2 on 2019-08-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190828_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='is_valide',
            new_name='is_valid',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='signator',
            new_name='signature',
        ),
    ]
