# Generated by Django 2.2.2 on 2019-09-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20190904_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='cityname',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='level',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='parent_id',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='city',
            name='code',
        ),
        migrations.RemoveField(
            model_name='city',
            name='first_letter',
        ),
    ]
