# Generated by Django 2.2.2 on 2019-09-04 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190904_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='cityname',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='pid',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='type',
            new_name='parent_id',
        ),
        migrations.AddField(
            model_name='city',
            name='first_letter',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
