# Generated by Django 2.2.2 on 2019-09-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190904_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('receiver', models.CharField(max_length=250)),
                ('province_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('district_id', models.IntegerField()),
                ('place', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=11)),
                ('tel', models.CharField(default='', max_length=11)),
                ('email', models.CharField(default='', max_length=50)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'address',
            },
        ),
    ]
