# Generated by Django 2.2.2 on 2019-09-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='email',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='tel',
            field=models.CharField(default='', max_length=11, null=True),
        ),
    ]
