# Generated by Django 2.2.2 on 2019-09-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190904_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.IntegerField(default=0),
        ),
    ]
